from typing import Final


DEFAULT_MODEL: Final = "gpt-5.6-luna"
DEFAULT_API_MAX_RETRIES: Final = 5

# Quality acceptance criteria for collected research.
RECENT_REVIEW_MAX_AGE_DAYS: Final = 365
MIN_RECENT_REVIEW_COUNT: Final = 5
MIN_REVIEW_SOURCE_SITES: Final = 2
MIN_IN_RANGE_CANDIDATES: Final = 5
DISCOVERY_TARGET_IN_RANGE_CANDIDATES: Final = 20
DEFAULT_DISCOVERY_ATTEMPTS: Final = 3
DEFAULT_REVIEW_ENRICHMENT_ATTEMPTS: Final = 27
TARGET_KATSUO_EVIDENCE_DOMAINS: Final = 3
DUPLICATE_LOCATION_THRESHOLD_KM: Final = 0.05
